add solution for 03-streams 02-line-split-stream
js-tasks-ru/nodejs-20200914-2_ssekats pull request #4
Opened 2020-09-29 14:33 UTC by Sergei-Sekatski

2020-09-29 14:40 UTC, jsru commented
Поздравляю, все задачи решены абсолютно верно
```diff
Стрим, разбивающий текст на строки
+ стрим разбивает данные по строкам
+ стрим корректно передает данные даже если чанк не завершается переводом строки
```

Добавляю преподавателя (@RidgeA) для код-ревью, посмотрим что он скажет :)

2020-09-29 20:19 UTC, RidgeA requested changes

2020-09-29 20:19 UTC, RidgeA commented on 03-streams/02-line-split-stream/LineSplitStream.js
> +let _currentString;
Подход с использованием глобальной переменной будет работать если используется только 1 экземпляр класса `LineSplitStream`
В реальности может использоваться несколько и в таком случае это может привести к тому что данны от предыдущего использования будут смешиваться с текущими данными или, в случае одновременного использования, они вообще будут перемешаны между собой.
Эту переменную лучше сделать свойством класса, в таком случае для каждого экземпляра класса будет своя отдельная переменная.

2020-09-29 20:19 UTC, RidgeA commented on 03-streams/02-line-split-stream/LineSplitStream.js
> +    try {
В данном случае блок try/catch лишний. Маловероятно, что в коде ниже будет ошибка, а если уж перестраховываться то нужно ошибку куда-то передавать. Иначе о ней никто не узнает. Скрывать ошибки это плохая практика.

2020-10-01 08:49 UTC, Sergei-Sekatski commented on 03-streams/02-line-split-stream/LineSplitStream.js
> +let _currentString;
Фиксанул

2020-10-01 08:50 UTC, Sergei-Sekatski commented on 03-streams/02-line-split-stream/LineSplitStream.js
> +    try {
фиксанул

2020-10-01 08:51 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @RidgeA

2020-10-01 09:56 UTC, RidgeA approved these changes

2020-10-01 09:56 UTC, merged